# -*- coding: utf-8 -*-
"""MTTR Comparison Plot with Labels and Highlighting (Updated)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JtWOmgRwNl5qOKbjfntYUrwaxCFrKrDW
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# --- 1. Generate Sample Data ---
weeks = [1, 2, 3, 4]
esb_sub_platforms = [f'ESB_Platform_{i}' for i in range(1, 8)]
etl_sub_platforms = [f'ETL_Platform_{i}' for i in range(1, 9)]

data = []
for week in weeks:
    for sub_platform in esb_sub_platforms:
        mttr = np.random.uniform(2.0, 15.0)
        data.append({'Week': week, 'Team': 'ESB', 'SubPlatform': sub_platform, 'MTTR': mttr})
    for sub_platform in etl_sub_platforms:
        mttr = np.random.uniform(1.5, 12.0)
        data.append({'Week': week, 'Team': 'ETL', 'SubPlatform': sub_platform, 'MTTR': mttr})

df = pd.DataFrame(data)

# Ensure consistent ordering of sub-platforms on the y-axis across all plots.
all_sub_platforms_ordered = esb_sub_platforms + etl_sub_platforms
df['SubPlatform'] = pd.Categorical(df['SubPlatform'], categories=all_sub_platforms_ordered, ordered=True)

# --- 2. Calculate Percentage Increase for Highlighting ---
# Filter data for Week 3 and Week 4
week3_data = df[df['Week'] == 3].set_index(['Team', 'SubPlatform'])['MTTR']
week4_data = df[df['Week'] == 4].set_index(['Team', 'SubPlatform'])['MTTR']

# Combine Week 3 and Week 4 data for comparison
comparison_df = pd.DataFrame({'MTTR_Week3': week3_data, 'MTTR_Week4': week4_data}).dropna()

# Calculate the percentage increase from Week 3 to Week 4
# Add a small epsilon to MTTR_Week3 to avoid division by zero if MTTR_Week3 is 0.
comparison_df['Percentage_Increase'] = ((comparison_df['MTTR_Week4'] - comparison_df['MTTR_Week3']) / (comparison_df['MTTR_Week3'] + 1e-6)) * 100

# Identify sub-platforms to highlight (where increase is > 10%)
highlight_threshold = 10
subplatforms_to_highlight = comparison_df[comparison_df['Percentage_Increase'] > highlight_threshold].index.tolist()

# --- 3. Plotting the Data ---
sns.set_theme(style="whitegrid")

# Explicitly define hue order to ensure consistent mapping
hue_categories = ['ESB', 'ETL']

g = sns.catplot(
    data=df,
    x='MTTR',
    y='SubPlatform',
    hue='Team',
    col='Week',
    kind='bar',
    orient='h',
    height=6,
    aspect=0.8,
    palette={'ESB': '#FF6347', 'ETL': '#4682B4'},
    col_wrap=4, # All 4 weeks in one row
    sharey=True,
    legend_out=True,
    hue_order=hue_categories # Use the defined hue order
)

# --- 4. Customize Plot Appearance: Add Data Labels and Highlight Bars ---

# Get the maximum MTTR value to set appropriate x-axis limits for labels
max_mttr = df['MTTR'].max()

# Iterate through each subplot (axes) in the FacetGrid
for ax_idx, ax in enumerate(g.axes.flat):
    week = ax_idx + 1 # Assuming week numbers start from 1 (Week 1, Week 2, etc.)

    # Extend x-axis limits to make space for data labels
    ax.set_xlim(right=max_mttr * 1.2) # Extend by 20% to accommodate labels

    # Iterate through the containers (groups of bars for each hue/team)
    for container_idx, container in enumerate(ax.containers):
        # Use the explicitly defined hue_categories to get the current team name
        current_team = hue_categories[container_idx]

        # Iterate through each individual bar (patch) in the container
        for bar_idx, bar in enumerate(container.patches):
            mttr_value = bar.get_width()
            y_pos = bar.get_y() + bar.get_height() / 2 # Y-position for text (centered on bar)

            # Add data label (MTTR value) to each bar
            ax.text(
                mttr_value + 0.3, # X-position slightly to the right of the bar end
                y_pos,
                f'{mttr_value:.1f}', # Format to one decimal place
                va='center', # Vertical alignment
                ha='left',   # Horizontal alignment
                fontsize=8,
                color='black'
            )

            # Highlighting logic for Week 4 bars
            if week == 4:
                # Get the sub-platform name for the current bar based on its index
                sub_platform_name = all_sub_platforms_ordered[bar_idx]

                # Check if this (team, sub-platform) pair should be highlighted
                if (current_team, sub_platform_name) in subplatforms_to_highlight:
                    bar.set_edgecolor('red') # Highlight with a red border
                    bar.set_linewidth(2.5)   # Make the border thicker

# Set labels and overall title
g.set_axis_labels("Mean Time To Restore (MTTR) in Hours", "Sub-Platform")
g.set_titles("Week {col_name}")
g.fig.suptitle("MTTR Comparison: ESB vs. ETL Teams by Sub-Platform (Weekly)", y=1.02, fontsize=16)

# Adjust the layout to prevent titles/labels from overlapping
plt.tight_layout(rect=[0, 0, 1, 0.98]) # Leaves space for the suptitle

# Save the plot to an image file
plt.savefig('mttr_comparison_plot_with_labels_highlighted.png')
plt.show()

